name: iOS Build and Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      # Installer la dernière version stable d'Xcode (qui est Xcode 15.x)
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      # Installer Ruby et Bundler
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.0"  # Remplacez "latest" par une version spécifique de Ruby

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      # Lancer les tests
      - name: Run Tests
        run: |
          # Utiliser Xcode 15.x avec un simulateur iPhone 14 Pro Max et iOS 16.2
          bundle exec fastlane ios unit_test platform=ios simulator='iPhone 14 Pro Max' os='16.2'
